<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="rahulshettyacademy.tests.ErrorValidationsSampleTest">
        <methods>
          <include name="ProductErrorValidation"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
          <include name="LoginErrorValidation"/>
        </methods>
      </class> <!-- rahulshettyacademy.tests.ErrorValidationsSampleTest -->
      <class name="rahulshettyacademy.tests.ErrorValidationsTest">
        <methods>
          <include name="ProductErrorValidation"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- rahulshettyacademy.tests.ErrorValidationsTest -->
      <class name="rahulshettyacademy.tests.SubmitOrderTest">
        <methods>
          <include name="submitOrder"/>
          <include name="tearDown"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- rahulshettyacademy.tests.SubmitOrderTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
